Models/ErrorViewModel.cs
using System;

namespace AspNetMVC.LabExercise1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
namespace AspNetMVC.LabExercise1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal TotalAmount {
            get
            {
                return this.Quantity * Price;
            }
            set
            {
                this.TotalAmount = value;
            }
        }
    }
}

Controllers/HomeController.cs
using AspNetMVC.LabExercise1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetMVC.LabExercise1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using AspNetMVC.LabExercise1.Services;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMVC.LabExercise1.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService _productService;

        public ProductController(ProductService productService)
        {
            _productService = productService;
        }

        public IActionResult List()
        {
            ViewData["ProductList"] = _productService.GetCatalog();
            ViewData["GrandTotal"] = _productService.GetGrandTotal();
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Product/List.cshtml
@using AspNetMVC.LabExercise1.Models;
@using System.Collections.Generic;
@{
    var products = ViewData["ProductList"] as List<Product>;
    var grandTotal = ViewData["GrandTotal"];
}

<div>
    <h2>Product List</h2>
    <table  class="table table-primary table-striped">
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Description</td>
            <td>Quantity</td>
            <td>Price</td>
            <td>Total Amount</td>
        </tr>
        @foreach(var product in products)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Description</td>
                <td>@product.Quantity</td>
                <td>@product.Price</td>
                <td>@product.TotalAmount</td>
            </tr>
        }
         <tr>
            <td colspan="4"></td>
            <td>Grand Total:</td>
            <td>@grandTotal</td>
        </tr>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetMVC.LabExercise1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetMVC.LabExercise1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="background-color: #f4f9ff; width: 100%; padding-top:16px">
        
        <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        </div>

    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AspNetMVC.LabExercise1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>